Repository snack-25/back, pull requests merged in 2025-04, with the labels that each got.

#221 ✨ feat: S3로 상품 이미지 업로드 로직 변경
  src/products/const/index.ts
  src/products/dto/create-product.dto.ts
  src/products/products.controller.ts
  src/products/products.module.ts
  src/products/products.service.ts
  src/shared/const/path.ts
  src/users/users.module.ts
Labels: api, BE

#226 Feature/96 김지연 0318products api 마무리
  src/products/products.service.ts
Labels: api, BE, chore

#232 swagger설정에 addBearerAuth() 설정 추가
  package.json
  pnpm-lock.yaml
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/budgets/budgets.controller.ts
  src/carts/carts.controller.ts
  src/categories/categories.controller.ts
  src/invitations/invitations.controller.ts
  src/order-requests/dto/approve-order-request.dto.ts
  src/order-requests/dto/getOrderRequest.dto.ts
  src/order-requests/order-requests.controller.spec.ts
  src/order-requests/order-requests.controller.ts
  src/order-requests/order-requests.module.ts
  src/order-requests/order-requests.service.spec.ts
  src/order-requests/order-requests.service.ts
  src/orders/orders.controller.ts
  src/products/dto/create-product.dto.ts
  src/products/products.controller.ts
  src/products/products.service.ts
  src/shared/const/RegExp.ts
  src/shared/swagger/SwaggerOptions.ts
  src/users/dto/response-user.dto.ts
  src/users/users.controller.ts
  src/users/users.service.ts
  src/wishlists/wishlists.controller.ts
Labels: api, auth, BE, chore, docs

#249 Fix linting issues Commenting type errors
  src/auth/auth.service.ts
  src/invitations/invitations.service.ts
  src/order-requests/dto/create-order-request.dto.ts
  src/order-requests/dto/reject-order-request.dto.ts
  src/order-requests/order-requests.controller.spec.ts
  src/order-requests/order-requests.controller.ts
  src/order-requests/order-requests.service.spec.ts
  src/order-requests/order-requests.service.ts
  src/users/dto/response-user.dto.ts
Labels: bug, BE, chore

#260 ✨ feat(shared): impl get user decorator
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/dto/auth.dto.ts
  src/main.ts
  src/order-requests/order-requests.controller.spec.ts
  src/order-requests/order-requests.controller.ts
  src/order-requests/order-requests.module.ts
  src/order-requests/order-requests.service.ts
  src/shared/decorators/get-user.decorator.ts
  src/shared/middleware/auth.middleware.ts
  src/shared/services/jwt.service.ts
  src/users/dto/user.dto.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: auth, BE, feat

#286 🎉 feat: 장바구니 예산,배송비조회 API
  src/carts/carts.controller.ts
  src/carts/carts.service.ts
  src/carts/dto/cart.interface.ts
  src/order-requests/order-requests.controller.ts
  src/order-requests/order-requests.service.ts
  src/shared/helpers/budget.helper.ts
Labels: api, BE

#295 ♻️ refactor: 로그인 메서드 파라미터 및 응답 데이터 수정
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/role.guard.ts
  src/products/dto/product.response.dto.ts
  src/products/products.controller.ts
  src/products/products.service.ts
  src/shared/middleware/auth.middleware.ts
Labels: api, auth, BE

#313 ♻️ feat(controller, service): 간소화된 '내 상품' 조회 로직
  src/products/products.controller.ts
  src/products/products.service.ts
Labels: api, BE
