Repository snack-25/back, pull requests merged in 2025-03, with the labels that each got.

#2 Fix/1-update-app-module
  src/app.module.ts
  src/auth/auth.module.ts
Labels: bug, BE

#4 Fix(prisma)/3-update-prisma-service
  package.json
  pnpm-lock.yaml
  prisma/schema/schema.prisma
  src/app.module.ts
  src/shared/prisma/prisma.service.ts
Labels: bug, BE

#10 🔧 chore(config): CORS 설정 도메인 업데이트
  src/main.ts
Labels: BE, chore

#18 주문 요청 API/주문 요청 내역 시딩
  prisma/const/orderRequestItems.ts
  prisma/seed.ts
  src/order-requests/dto/approve-order-request.dto.ts
  src/order-requests/dto/create-order-request.dto.ts
  src/order-requests/dto/reject-order-request.dto.ts
  src/order-requests/order-requests.controller.ts
  src/order-requests/order-requests.service.ts
Labels: api, BE

#20 Cd(workflow)/8-deploy-to-aws-ec2
  .github/workflow/deploy.yml
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
  src/app.controller.ts
  src/app.service.ts
  src/order-requests/order-requests.controller.ts
Labels: BE, chore, deps

#22 👷 ci(deploy): EC2 배포를 위한 GitHub Actions 경로 오타 수정
  .github/workflows/deploy.yml
Labels: BE, chore

#24 👷 ci(deploy): pnpm install 명령어의 lockfiles 옵션 수정
  .github/workflows/deploy.yml
Labels: BE, chore

#26 👷 ci(husky): CI 환경에서 후크 스킵 기능 추가 및 코드 정리
  .husky/check-pnpm.sh
  .husky/commit-msg
  .husky/detect-package-manager.sh
  .husky/pre-commit
  .husky/pre-push
  .husky/set-node.sh
Labels: BE, chore

#28 👷 ci(husky): change posix compatible script
  .husky/check-pnpm.sh
  .husky/commit-msg
  .husky/detect-package-manager.sh
  .husky/pre-commit
  .husky/pre-push
  .husky/set-node.sh
Labels: BE, chore

#30 👷 ci(husky): CI 환경 체크 스킵
  .husky/set-node.sh
Labels: BE, chore

#32 👷 ci(deploy): husky prepare 스크립트 건너뛰기 추가
  .github/workflows/deploy.yml
Labels: BE, chore

#34 👷 chore(dependencies): @prisma/client 및 prisma 패키지 추가
  package.json
Labels: BE, chore

#36 👷 chore(dependencies): pnpm-lock.yaml 업데이트 및 불필요한 의존성 제거
  pnpm-lock.yaml
Labels: BE, chore

#39 👷 ci(deploy): 빌드에 필요한 devDependencies 설치 추가
  .github/workflows/deploy.yml
Labels: BE, chore

#41 👷 ci(deploy): 배포 전 현재 배포 백업 로직 수정
  .github/workflows/deploy.yml
Labels: BE, chore

#43 👷 ci(deploy): 배포 스크립트 개선 및 환경 변수 검증 추가
  .github/workflows/deploy.yml
Labels: BE, chore

#45 👷 ci(deploy): PM2 설정 및 GPG 비밀번호 추가
  .github/workflows/deploy.yml
Labels: BE, chore

#50 👷 ci(deploy): pnpm 설치 옵션에서 --frozen-lockfile 제거
  .github/workflows/deploy.yml
Labels: BE, chore

#52 👷 ci(deploy): 환경 변수 마스킹 및 NODE_ENV 추가
  .github/workflows/deploy.yml
Labels: BE, chore

#54 👷 ci(deploy): 배포 스크립트 타임아웃 및 로그 확인 추가
  .github/workflows/deploy.yml
Labels: BE, chore

#56 👷 ci(deploy): 배포 스크립트에서 PM2 명령어 수정
  .github/workflows/deploy.yml
Labels: BE, chore

#58 👷 ci(deploy): NVM 및 Corepack 설정 추가
  .github/workflows/deploy.yml
Labels: BE, chore

#63 👷 ci(deploy): 배포 스크립트에서 Prisma 명령어를 pnpm으로 변경 및 GPG 복호화 로그 추가
  .github/workflows/deploy.yml
Labels: BE, chore

#83 Fix/11-improve-dotenv-stuff
  .github/workflows/deploy.yml
  package.json
  pnpm-lock.yaml
  src/app.controller.ts
  src/app.service.ts
  src/carts/carts.controller.ts
  src/carts/dto/update-cart.dto.ts
  tsconfig.json
Labels: BE, chore

#85 🔧 chore(deploy): 헬스 체크 URL에서 호스트 변수 사용
  .github/workflows/deploy.yml
Labels: BE, chore

#89 🔧 chore(dependencies): dotenv-cli 추가 및 @babel/helpers 버전 업데이트
  package.json
  pnpm-lock.yaml
Labels: BE, chore

#91 🔧 chore(deploy): EC2 배포 스크립트 개선
  .github/workflows/deploy.yml
Labels: BE, chore

#93 🔧 chore(deploy): 배포 스크립트 리팩토링 및 오류 처리 개선
  .github/workflows/deploy.yml
Labels: BE, chore

#95 🔧 chore(deploy): 배포 검증 대기 시간 증가
  .github/workflows/deploy.yml
Labels: BE, chore

#100 🔧 chore(deploy): 배포 스크립트 개선 및 로그 관리 추가
  .github/workflows/deploy.yml
Labels: BE, chore

#102 🔧 chore(deploy): SSH 키 페어 타입을 비밀로 관리하고 배포 스크립트 개선
  .github/workflows/deploy.yml
Labels: BE, chore

#104 🔧 chore(deploy): 배포 스크립트에서 NVM 소스 추가 및 PM2 상태 확인 개선
  .github/workflows/deploy.yml
Labels: BE, chore

#106 🔧 chore(deploy): 배포 검증 로직 개선 및 SSH 옵션 추가
  .github/workflows/deploy.yml
Labels: BE, chore

#108 🔧 chore(deploy): GIT_COMMIT_SHA 환경 변수 추가 및 마스킹 제거
  .github/workflows/deploy.yml
Labels: BE, chore

#112 Chore(swagger)/111-rename-backend-endpoint
  src/main.ts
  src/order-requests/order-requests.service.ts
Labels: BE, chore

#114 🔧 chore(deploy): 건강 검사 엔드포인트 수정
  .github/workflows/deploy.yml
Labels: BE, chore

#116 🔧 chore(deploy): 배포 스크립트 수정 및 Prisma 배포 로그 개선
  .github/workflows/deploy.yml
Labels: BE, chore

#118 🔧 chore(deploy): 배포 스크립트 개선 및 로그 마스킹 처리 수정
  .github/workflows/deploy.yml
Labels: BE, chore

#120 🔧 chore(deploy): PM2 상태 확인 및 환경 설정 추가
  .github/workflows/deploy.yml
Labels: BE, chore

#122 🔧 chore(deploy): PM2 경로 설정 및 프로세스 관리 개선
  .github/workflows/deploy.yml
Labels: BE, chore

#124 🔧 chore(deploy): NVM 및 Node.js 환경 설정 추가
  .github/workflows/deploy.yml
Labels: BE, chore

#126 🔧 chore(deploy): 건강 검사 스크립트 개선 및 불필요한 NVM 설정 제거
  .github/workflows/deploy.yml
Labels: BE, chore

#128 🔧 chore(deploy): 건강 검사 스크립트의 SSH 명령어 수정
  .github/workflows/deploy.yml
Labels: BE, chore

#130 🔧 chore(deploy): PM2 설치 및 경로 설정 개선
  .github/workflows/deploy.yml
Labels: BE, chore

#132 🔧 chore(deploy): Node.js 및 pnpm 환경 설정 추가
  .github/workflows/deploy.yml
Labels: BE, chore

#134 🔧 chore(deploy): pnpm 환경 설정 및 영구 적용 추가
  .github/workflows/deploy.yml
Labels: BE, chore

#138 🔧 chore(deploy): SHELL 환경 변수 설정 및 pnpm 설치 로직 제거
  .github/workflows/deploy.yml
Labels: BE, chore

#139 🔧 chore(deploy): pnpm 설치 로직 개선 및 환경변수 설정 최적화
  .github/workflows/deploy.yml
Labels: BE, chore

#140 🔧 chore(deploy): pnpm 환경변수 설정 및 중복 로직 제거
  .github/workflows/deploy.yml
Labels: BE, chore

#141 🔧 chore(deploy): Node.js 버전 매트릭스 추가 및 pnpm 환경변수 경로 수정
  .github/workflows/deploy.yml
Labels: BE, chore

#142 🔧 chore(deploy): Node.js 설정 및 pnpm 설치 로직 정리
  .github/workflows/deploy.yml
Labels: BE, chore

#143 🔧 chore(deploy): curl 요청 및 환경 변수 설정 개선
  .github/workflows/deploy.yml
Labels: BE, chore

#144 🔧 chore(deploy): 건강 검사 및 환경 변수 설정 개선
  .github/workflows/deploy.yml
Labels: BE, chore

#145 🔧 chore(deploy): PM2 상태 확인 로직 제거 및 코드 간소화
  .github/workflows/deploy.yml
Labels: BE, chore

#148 Fix(deploy)/146 add seeding process
  .github/workflows/deploy.yml
Labels: BE, chore

#152 🔧 chore(cors): CORS 설정 업데이트
  src/main.ts
Labels: BE, chore

#156 ✨ feat(prisma): Wishlist 스키마 추가
  prisma/migrations/20250320043440_add_wishlist_model/migration.sql
  prisma/schema/Wishlist.prisma
Labels: BE, chore

#158 ✨ feat(prisma): 주문 요청 및 사용자 데이터 시드 개선
  prisma/const/orderRequestItems.ts
  prisma/seed.ts
  src/shared/swagger/SwaggerOptions.ts
Labels: BE, chore, database

#161 ✨ feat(prisma): 시드 스크립트 개선 및 불필요한 파일 삭제
  package.json
  prisma/const/orderRequestItems.ts
  prisma/const/products.ts
  prisma/seed.ts
Labels: BE, chore, database

#163 ✨ chore(package): 프로덕션 시드 스크립트 수정
  package.json
Labels: BE, chore, database

#198 🚀 ci(deploy): 배포 시 우편번호 seed 실패 로직 수정
  .github/workflows/deploy.yml
  package.json
  pnpm-lock.yaml
  prisma/seed.ts
Labels: BE, chore, database

#202 🚀 ci(deploy): 배포 시 백업 파일 생성 및 관리 로직 개선
  .github/workflows/deploy.yml
Labels: BE, chore

#200 Feature/96 김지연 0318products api 마무리
  prisma/const/categories.json
  prisma/const/companies.json
  prisma/const/products.json
  prisma/const/sub-categories.json
  prisma/const/users.json
  prisma/seed.ts
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/products/products.module.ts
  src/shared/const/path.ts
  src/users/dto/user.dto.ts
Labels: BE, chore, database

#207 🚀 ci(deploy): 의존성 설치 및 배포 스크립트 개선
  .github/workflows/deploy.yml
Labels: BE, chore, deps
